version: '3.7'

services:
  gateway-envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile-envoy
    ports:
      - '10000:10000'
      - '9901:9901'
      - '8080:8080'
      - '8001:8001'
  whereisgoserver:
    build:
      context: ./server
      dockerfile: Dockerfile-server
    ports:
      - '50051:50051'
    env_file:
      - .env
  whereisgoclient:
    build:
      context: ./client
      dockerfile: Dockerfile-client
    ports:
      - '5173:5173'
  whereisgodata:
    build:
      context: ./whereisgodata
      dockerfile: Dockerfile
    env_file:
      - .env