FROM golang:1.21-alpine AS Build

WORKDIR /app

# Copy only the necessary files for go mod download
COPY go.mod .
COPY go.sum .

# Download dependencies
RUN go mod download

# Copy the entire project into the container
COPY . .

EXPOSE 50051

# Build the Go application
RUN go build -o /whereisgo /app/cmd/whereisgo/whereisgo.go

FROM alpine:latest

WORKDIR /

# Copy the binary from the BuildStage
COPY --from=Build /whereisgo /whereisgo

EXPOSE 50051

ENTRYPOINT ["/whereisgo"]